version 3.3.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13,11 +13,25 @@ PKG_TEST_HEADER="<v8.h>"
 PKG_LIBS="-lv8 -lv8_libplatform"
 PKG_CFLAGS="-I/usr/include/v8 -I/usr/include/v8-3.14"
 
-# Find compiler
+# Use CXX14 when available, required as of libv8 version 8.7.80
+CXX14=$(R CMD config CXX14)
+
+# Upon failure, some versions of R return error, others succes with empty output
+if [ $? -eq 0 ] && [ "$CXX14" ]; then
+echo "Using C++14"
+CXX_STD=CXX14
+CXX="$CXX14 $(${R_HOME}/bin/R CMD config CXX14STD)"
+CXXFLAGS=$(${R_HOME}/bin/R CMD config CXX14FLAGS)
+else
+echo "Not using C++14"
+CXX_STD=CXX11
+CXX="$(${R_HOME}/bin/R CMD config CXX)"
 CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
+fi
+
+# Find compiler
 CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
 LDFLAGS=$(${R_HOME}/bin/R CMD config LDFLAGS)
-CXX=$(${R_HOME}/bin/R CMD config CXX)
 CXXCPP="$CXX -E"
 
 # Check for custom locations
@@ -69,7 +83,7 @@ fi
 
 # Test if we need to enable pointer compression (Usually 8.4 and up)
 echo "Running feature test for pointer compression..."
-${CXX} ${CPPFLAGS} ${PKG_CFLAGS} -DV8_ENABLE_CHECKS tools/test.cpp -o pctest ${LDFLAGS} ${PKG_LIBS}
+${CXX} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -DV8_ENABLE_CHECKS tools/test.cpp -o pctest ${LDFLAGS} ${PKG_LIBS}
 { ./pctest; } 2>> configure.log
 if [ $? -eq 0 ]; then
   echo "Pointer compression not needed"
@@ -81,5 +95,5 @@ fi
 rm -Rf pctest*
 
 # Assume a modern V8 API
-sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
+sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" -e "s|CXX11|${CXX_STD}|" src/Makevars.in > src/Makevars
 exit 0
